Repository courselab/coral, pull requests merged in 2024-11, with the labels that each got.

#52 feat: adding stylized head and tail
  coral.py
Labels: feat

#60 Add new movement keys
  coral.py
Labels: feat

#100 fix: adding byteorder parameter to byte conversion functions
  coral.py
Labels: bug

#106 code cleanup: Splitting project in more files
  app/__init__.py
  app/apple.py
  app/config.py
  app/energybar.py
  app/game.py
  app/main.py
  app/orange.py
  app/snake.py
  coral.py
Labels: ref

#111 Feat: coloring entire snake on death
  app/apple.py
  app/config.py
  app/main.py
  app/snake.py
Labels: feat
